spring:
  application:
    name: config-server

  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://C:\Users\f.yazdani\CentralRepo
management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh, beans, env, info



eureka:
  instance:
    hostname: localhost
    non-secure-port: 8085
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka
server:
  port: 8088

