my:
  prop: is this from web - 2 - dev - 1 test kooft qqq




eureka:
  instance:
    hostname: localhost
    non-secure-port: 8085
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh, beans, env, info


server:
  port: 9094
