my:
  prop: this si from web - 2 - prod

eureka:
  instance:
    hostname: localhost
    non-secure-port: 8085
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka
server:
  port: 9096
